version: '3.1'

services:
  db:
    container_name: postgresql
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_PASSWORD: kj2aBv6f33cZ

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - './backend:/app'
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - db
  
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - './frontend/public:/app/public'
      - './frontend/src:/app/src'
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - backend